info:
  app: @project.name@
  version: @project.version@
# server configuration
server:
  port: 8000
  servlet:
    context-path: /kbase-template
spring:
  # register to kbase-monitor
  application:
    name: @project.name@
    boot:
      admin:
        client:
          url: http://172.16.8.139:8899/kbase-monitor
          username: kbs
          password: kbs123$
  cache:
    redis:
      cache-null-values: false
  # redis support
  redis:
    port: 6379
    host: 172.16.8.139
    timeout: 3000
  # hikari support
  datasource:
    username: philips
    password: philips
    name: hikari
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.1.119:3306/philips
    hikari:
      connection-timeout: 1800000
      auto-commit: true
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      connection-init-sql: select 1 from dual
  jpa:
    show-sql: true

# kbs related configuration
kbs:
  jwt:
    tokenHead: Bearer
    expireInMinute: 30
    AuthHeader: Authorization
    refreshRemainLeftMinute: 5
    issuer: kbase-jwt
# expose info
management:
  server:
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: *